trainer:
  max_epochs: 48
  accumulate_grad_batches: 1
model:
  init_args:
    backbone_name: eva02_B_ade_seg_upernet_sz512
    grad_checkpointing: false
data:
  init_args:
    img_size: 512
    batch_size: 8