trainer:
  accumulate_grad_batches: 4
model:
  init_args:
    backbone_name: swinv2_base_window12to24_192to384.ms_in22k_ft_in1k
data:
  init_args:
    crop_size: 768
    crop_size_z: 6
    img_size: 768
    img_size_z: 6
    batch_size: 2
