program: run/main_cv.py
command:
  - ${env}
  - /root/miniconda3/envs/scrolls/bin/python
  - ${program}
  - fit
  - --config
  - run/configs/2d/unet-2d.yaml
  - ${args}
method: grid
parameters:
  trainer.max_epochs:
    distribution: categorical
    values: 
    - 48
  model.init_args.backbone_name:
    distribution: categorical
    values: 
    - convnextv2_base.fcmae_ft_in22k_in1k_384
    - maxvit_rmlp_base_rw_384.sw_in12k_ft_in1k
  data.init_args.img_size:
    distribution: categorical
    values:
    - 384
  data.init_args.mix_transform_name:
    distribution: categorical
    values:
    - cutmix
    - mixup
    - cpp
    - null