seed_everything: 0
trainer:
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: scrolls
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 1
        monitor: v_f05
        every_n_epochs: 1
        mode: max
        save_on_train_epoch_end: false
        save_last: true

  # limit_train_batches: 10
  # limit_val_batches: 10
  max_epochs: 16
  num_sanity_val_steps: 0
  accumulate_grad_batches: 1
  reload_dataloaders_every_n_epochs: 1
  log_every_n_steps: 1
  gradient_clip_val: 1000
  check_val_every_n_epoch: 1
  precision: 16-mixed

  gradient_clip_algorithm: norm
  deterministic: true
  benchmark: false
  enable_checkpointing: true

  fast_dev_run: false
  profiler: null
  detect_anomaly: false
  
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  enable_progress_bar: null
  enable_model_summary: null
  inference_mode: true
  use_distributed_sampler: true
  barebones: false
  plugins: null
  sync_batchnorm: false
  default_root_dir: null
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
model:
  class_path: src.model.modules.SegmentationModule
  init_args:
    type_: 2d
    decoder_attention_type: scse
    in_channels: 6
    backbone_name: null
    pos_weight: 1.0
    label_smoothing: 0.0
    optimizer_init: 
      class_path: torch.optim.AdamW
      init_args:
        weight_decay: 1e-6
        lr: 1e-4
        eps: 1e-08
    lr_scheduler_init:
      class_path: src.utils.lr_scheduler.PiecewiceFactorsLRScheduler
      init_args:
        milestones: [0, 0.1, 1.0]
        pieces:
          - class_path: src.utils.lr_scheduler.LinearLRSchedulerPiece
            init_args:
              start_lr: 1e-1
              stop_lr: 1
          - class_path: src.utils.lr_scheduler.CosineLRSchedulerPiece
            init_args:
              start_lr: 1
              stop_lr: 1e-2
    pl_lrs_cfg:
      interval: step
      frequency: 1
    finetuning: null
    lr_layer_decay: 1.0
    log_norm_verbose: true
    n_bootstrap: 0
    skip_nan: false
    prog_bar_names: 
      - f05
data:
  class_path: src.data.datamodules.SurfaceVolumeDatamodule
  init_args:
    surface_volume_dirs: 
      - /workspace/data/fragments_downscaled_2/train/1
      - /workspace/data/fragments_downscaled_2/train/2
      - /workspace/data/fragments_downscaled_2/train/3
    surface_volume_dirs_test: null
    val_dir_indices: 2
    crop_size: 256
    crop_size_z: 6
    img_size: 256
    img_size_z: 6
    resize_xy: crop
    use_imagenet_stats: true
    batch_size: null
    batch_size_full: null
    batch_size_full_apply_epoch: null
    num_workers: 4
    pin_memory: false
    prefetch_factor: 2
    persistent_workers: true
